### PR TITLE
Add :compilation_debug config option

### LINKED ISSUE #478: Add option to disable compilation logs
I suggest to add an option to disable these logs:
```
14:27:41.766 [debug] compiling storybook file: core_components/button.story.exs

14:27:41.776 [debug] compiling storybook file: core_components/flash.story.exs

14:27:41.787 [debug] compiling storybook file: core_components/header.story.exs

14:27:41.798 [debug] compiling storybook file: core_components/input.story.exs

14:27:41.810 [debug] compiling storybook file: core_components/list.story.exs

14:27:41.820 [debug] compiling storybook file: core_components/modal.story.exs

14:27:41.831 [debug] compiling storybook file: core_components/table.story.exs

14:27:41.850 [debug] compiling storybook file: examples/chat_components.story.exs

14:27:41.908 [debug] compiling storybook file: examples/core_components.story.exs
```

Also these logs don't seem to take into account my config `config :logger, level: :warning` in test.

### PR DESCRIPTION
**Pull request by stefanluptak**
Closes #478

I had to make the `opts` available a bit deeper in the code, to read the `:compilation_debug` config option, but otherwise it seems to be a straightforward fix.

I am happy to adjust it based on your review or feel free to do it by yourself.

Thanks. :-)

### CODE REVIEW

**Comment by stefanluptak** [comment]
Sorry for the multiple force pushes after creating this PR. I did this change in my `deps` dir and then copied it to my fork and didn't realize the `main` is different from the latest released version, so I had to do a few tweaks afterwards. 😬

**Comment by stefanluptak** [comment]
Oh, now I can see the failing tests. (I wonder if I missed it previously, or it just didn't run?) Anyway, I can fix them, I think. :-)

**Comment by cblavier** [comment]
No worry.
I have to manually trigger CI for external PR

**Review by cblavier — APPROVED** [review]

**Comment by stefanluptak** [comment]
OK, the coverage stuff is new for me. Should I fix it. :-)

**Comment by cblavier** [comment]
Thanks for your PR! 🙏
I guess you can add a new test to `ExsCompilerTest` and assert that there is a log captured with the option set to true, no log otherwise

**Review by cblavier — CHANGES_REQUESTED** [review]
Thanks for your PR! 🙏
I guess you can add a new test to ExsCompilerTest and assert that there is a log captured with the option set to true, no log otherwise

**Comment by cblavier** [comment]
merged 🔥 thanks a lot!

**Pull request merged**
